version: "3.8"
services:
  expense_tracker_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    stop_signal: SIGINT
    container_name: expense_tracker_api_service
    image: expense_tracker_backend
    ports:
      - "3080:3080"
    # ? For automatically updating the container (for development only)
    volumes:
      - .:/app
    restart: always

  expense_tracker_database:
    image: mongo:4.4
    container_name: expense_tracker_db_service
    ports:
      - "27017:27017"
    volumes:
      - ~/data/expense_tracker/db:/data/db
    restart: unless-stopped